name: sqlserver


services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    restart: always
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: Rootroot10
      MSSQL_PID: Developer
      MSSQL_USER: SA
    networks:
      - db_net
      #volumes:
      #- sqlserver_data1:/var/opt/mssql
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    #command: /opt/DbScripts/init.sh
    command: sh -c "chmod +x /opt/DbScripts/init.sh && /opt/DbScripts/init.sh"
    #tty: true
    stdin_open: true
    networks:
      - db_net
    volumes:
      - ./DbScripts:/opt/DbScripts
# volumes:
#   sqlserver_data1:

networks:
  db_net:
    name: db_net
